---
apiVersion: v2
description: Corebot for Frontier-MC
name: fnt-corebot
version: 1.0.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: ChipWolf
    email: hello@chipwolf.uk
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.0
